/*
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1-nginx-deployment
  labels:
    app: app1-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app1-nginx
  template:
    metadata:
      labels:
        app: app1-nginx
    spec:
      spec:
      containers:
        - name: acrdemo-localdocker
          image: myregistryterra.azurecr.io/kube-nginx-acr:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 80
# To schedule pods on based on NodeSelectors
      nodeSelector:
        app: system-app


apiVersion: v1
kind: Service
metadata:
  name: app1-nginx-clusterip-service
  labels:
    app: app1-nginx
spec:
  type: LoadBalancer
  selector:
    app: app1-nginx
  ports:
    - port: 80
      targetPort: 80
*/
